on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      version:
        description: 'Provide release tag, eg. v4.9'
        type: string
        required: true
    
env:
  VERSION: ${{ inputs.version }}

run-name: DATV-Red release v${{ inputs.version }}
jobs:
  compact_release:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # environment: plutosdr-fw-ci
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        clean: true
        # submodules: recursive
    - name: make release directory
      shell: bash
      run: |
        mkdir Release
        7z a -t7z -mx=9 ./Release/DATV-Red-v$VERSION.7z *
    # - uses: milliewalky/setup-7-zip@v1
    #   with:
    #     args: 7z a -t7z -mx=9  ./Release/
      
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: release-v${{ inputs.version }}
        title: Release-v${{ inputs.version }}
        prerelease: false
        files: |
            Release/**.7z
